### ISSUE TITLE
Attachments are deleted on sync

### ISSUE THREAD

**Issue by danielo515** [wshallum/couchadaptor#11]
Attachment info is stored as a field of the document that is not the id neither the revision and is not part of the fields object (so TW does not process it). Because of this, when a new version of the tiddler is uploaded this information is lost.

According to couchdb documentation:
>Note that the "stub":true attribute denotes that this is not the complete attachment. Also, note the length attribute added automatically. When you update the document you must include the attachment stubs or CouchDB will delete the attachment.

We should add the attachments info when updating the tiddler.

**Comment by wshallum** [comment]
Hi Daniel,

Looking at the API here: http://docs.couchdb.org/en/1.6.1/api/document/common.html it does not seem to be possible to POST to a document and update select fields only. The attachments are not currently included but it is possible to get them by passing `attachments=true` on GET if that is required. I really don't recommend you have fields outside of what TW processes, but if you do they should probably be processed in the same way as `_rev` (by putting them into TW fields after GET and removing them before PUT).

Also, I have added you as collaborator to this repo so you can make your changes directly if you want. The honest truth is that this was just an interesting proof of concept for me but I don't actually use it now (I still use TW classic on local files...). Since you actually use it, you would be best placed to make future changes. Feel free to fork if you want and I'll put a note pointing people to your fork.

Thanks,
William

**Comment by danielo515** [comment]
Regarding this topic, here is what documentation says:

>Note that the "stub":true attribute denotes that this is not the complete attachment. Also, note the length attribute added automatically. When you update the document you must include the attachment stubs or CouchDB will delete the attachment.

So we have to store the attachment information, and not, the complete attachment is not included. We should treat this as a bug because we are using the API in the wrong way

**Comment by danielo515** [comment]
Regarding the other topics in this issue:

>Also, I have added you as collaborator to this repo so you can make your changes directly if you want. 

Yes, I noticed that, thank you very much! This is the first time someone adds me as a contributor (despite tiddlywiki) and that made me feel, well, like a more real developer ( but I'm not :smile: )

> The honest truth is that this was just an interesting proof of concept for me but I don't actually use it now (I still use TW classic on local files...). Since you actually use it, you would be best placed to make future changes.

I can understand this. I can continue fixing bugs and pushing by my own. But if you don't mind I would like to discuss with you new features and I would love to have your opinion on bug reports and that kind of things. You have demonstrated to have a good sense of doing things the right way, and I find your comments very valuable.

> Feel free to fork if you want and I'll put a note pointing people to your fork.

I actually did for being able to make pull requests. But I don't want to feel like I'm stealing your work, in fact the plugin is yours, and I just added some "details". Also I feel like any project is more open source and has more personality if it is maintained by more than one person: if there is only one developer the project is the developer, but if there is more than once the project has its own identity.

Having said that, I will proceed as you prefer.

**Comment by wshallum** [comment]
Re: attachments. I did not foresee people using this on arbitrary documents (and the adaptor never saves attachments on its own, so it is not technically the adaptor's fault)

If attachments are required by your app, can you think of some way to store them in a TW field? Then we can convert the stubs to TW field and back again in the `convert*` functions, just like _rev and the revision field.

Thanks,
William

**Comment by danielo515** [comment]
Hello William 

I don't know what do you mean with "my application". This problem have been reported in TW Google group by an user that is testing the adaptor. He got the idea of manually adding an attachment to a tiddler document, and then reference that attachment with the _canonical_uri field in the same tiddler. This way you can for example reference images and PDF documents without actually embedding them in the TW document,which is much efficient. He thought in adding the file as an attachment of the tiddler document to link them together. And I have to admit that I find it like a good idea. 

Maybe in the future we can automate this process, but I envision it like automatically uploading the file as an attachment to the tiddler and reference it by url, so at the end the adaptor should be able to deal with tiddlers with attachments. 

Regards

**Comment by danielo515** [comment]
Just for reference here is the topic I'm talking about :
https://groups.google.com/forum/m/#!topic/tiddlywiki/pZzttVrh5Kg

**Comment by wshallum** [comment]
My apologies for that. I thought this was your own problem. I don't really follow the TW Group.

That's an interesting idea but as I said earlier, CouchDB does not handle partial updates so the attachments have to go too.

I wonder if it might be possible to have pluggable conversion code so that people doing "interesting" things can implement their own attachment-preserving conversions.

**Comment by danielo515** [comment]
Hello @wwshallum

As I said in a comment above  
https://github.com/wshallum/couchadaptor/issues/11#issuecomment-104860587

When you fetch de document you don't get the attachment, just an object that holds some information about the object. So we don't need to handle attachments, just make sure we re upload the document with the appropriate attachment object (like we do with revision) to avoid couchdb deleting the attachment. Easy!
